feat: support different architectures when copying images
cdklabs/cdk-ecr-deployment pull request #570
Opened 2024-03-15 20:54 UTC by uncledru

Fixes #568 

Currently we can only copy images for the `amd64` architecture. [copy supports `ArchitectureChoice`](https://github.com/containers/image/blob/v5.21.0/types/types.go#L579) which is leverage in this PR. If no `Architecture` is provided the current behavior applies (uses the platform architecture, which is x86).

2024-05-01 02:50 UTC, deepend-dev commented
Great PR @uncledru. Even I am looking for this feature.

2024-05-01 02:53 UTC, deepend-dev commented
It will be great if @wchaws can look into this

2024-08-02 13:28 UTC, uncledru commented
also tagging @rix0rrr

2024-08-12 13:39 UTC, AdamPavlat commented
Hi, awesome and useful feature, please make it happen soon. 😄 Thanks.

2024-09-12 19:21 UTC, BwL1289 commented
Is there an update on this?

2024-10-08 09:45 UTC, mrgrain commented on package.json
> +  "version": "3.0.0",
please revert

2024-10-08 09:45 UTC, mrgrain commented on lambda/Dockerfile
why this change?

2024-10-08 09:46 UTC, mrgrain commented on lambda/main_test.go
please add a new test case using and asserting the new feature, keeping the old test case as it was.

If the old test case also needs to be changed, please explain why.

2024-10-08 09:46 UTC, mrgrain commented on lambda/utils.go
> +func IsValidGOARCH(arch string) bool {
Where is this used?

2024-10-08 09:47 UTC, mrgrain commented on publish-ark-image.sh
what is this file doing? Why was it added?

2024-10-08 09:47 UTC, mrgrain commented on test/example.ecr-deployment.ts
please add e new test.

2024-10-08 10:25 UTC, mrgrain requested changes
This is good. Some housekeeping comments.

We should also include `OSChoice` and `VariantChoice` as well.

https://github.com/containers/image/blob/v5.21.0/types/types.go#L579-L583

2024-10-08 10:26 UTC, mrgrain commented on src/index.ts
> +   * The architecture of the docker images to copy.
```suggestion
   * The architecture of the docker images to copy.
   *
   * @default "x64"
```

2024-10-08 10:27 UTC, mrgrain commented on src/index.ts
> +        Architecture: props.architecture,
I reckon we should fix this and move away from defaulting to the lambda architecture to explicitly defining a default here.

2025-01-08 09:59 UTC, mrgrain commented
Superseded by https://github.com/cdklabs/cdk-ecr-deployment/pull/961

2025-01-08 09:59 UTC, closed without merging